[workspace]
members = [
    "quartzite",
    "quartzite-core",
    "quartzite-macros",
    "quartzite-runtime",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Marat Bukharov <marat.buharov@gmail.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/maratik123/quartzite"
