[package]
name = "quartzite-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Application runtime, event loop, and object tree for quartzite"

[dependencies]
parking_lot           = "0.12"
quartzite-core        = { path = "../quartzite-core" }
quartzite-event-types = { path = "../quartzite-event-types" }
quartzite-macros      = { path = "../quartzite-macros" }
slotmap               = "1"
thiserror             = "2"
tracing               = { version = "0.1", features = ["log"] }

[dev-dependencies]
env_logger = "0.11"
itertools = "0.14"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
rustc-args = ["--cfg", "docsrs"]
