//! GPU snapshot tests for built-in widgets and layouts.
//!
//! Each test builds a deterministic widget (or layout), drives it through
//! a 64x64 [`RenderHarness`], and compares the readback to a committed
//! golden under `tests/snapshots/<backend>/<name>.png` via
//! [`support::snapshot_assert`] / [`support::snapshot_widget`].
//!
//! v1 goldens encode the wgpu clear-colour state (the renderer is a
//! no-op skeleton today). They get regenerated by follow-up render PRs
//! as `WidgetExt::paint` overrides and `VelloPainter` draw methods land.

mod support;

use quartzite_core::ObjectId;
use quartzite_renderer::RenderHarnessBuilder;
use quartzite_widgets::{BoxLayout, Button, Direction, GridLayout, Label, LineEdit};

use support::{snapshot_assert, snapshot_widget};

/// Canvas size shared by all v1 snapshots. Matches the design's "64x64
/// or 128x128" guidance — 64 keeps the committed PNGs small.
const CANVAS: u32 = 64;

/// Constructs a 64x64 harness or skips the test when no GPU adapter is
/// available locally. Returning `Option` lets the test exit cleanly when
/// `SKIP_RENDER_SNAPSHOT=1` is set or the box has no driver.
fn harness_or_skip(name: &str) -> Option<quartzite_renderer::RenderHarness> {
    if std::env::var_os("SKIP_RENDER_SNAPSHOT").is_some_and(|v| !v.is_empty()) {
        eprintln!("{name}: SKIP_RENDER_SNAPSHOT set; skipping");
        return None;
    }
    match RenderHarnessBuilder::new(CANVAS, CANVAS).build() {
        Ok(h) => Some(h),
        Err(e) => {
            eprintln!("{name}: no GPU adapter available ({e}); skipping");
            None
        }
    }
}

#[test]
fn label_renders() {
    let Some(mut harness) = harness_or_skip("label_renders") else {
        return;
    };
    let label = Label::new("test".into());
    snapshot_widget(&mut harness, "label", &label);
}

#[test]
fn button_renders() {
    let Some(mut harness) = harness_or_skip("button_renders") else {
        return;
    };
    let button = Button::new("OK".into());
    snapshot_widget(&mut harness, "button", &button);
}

#[test]
fn line_edit_renders() {
    let Some(mut harness) = harness_or_skip("line_edit_renders") else {
        return;
    };
    let mut edit = LineEdit::new();
    edit.set_text("hello".into());
    snapshot_widget(&mut harness, "line_edit", &edit);
}

#[test]
fn box_layout_renders() {
    // BoxLayout / GridLayout are not WidgetExt impls — they distribute
    // geometry across child widgets via a resolver. The snapshot tests
    // exercise the layout's construction + child registration path,
    // then capture the harness's clear-colour image (the renderer is a
    // no-op for v1 regardless of which widgets are in the layout).
    let Some(mut harness) = harness_or_skip("box_layout_renders") else {
        return;
    };
    let mut layout = BoxLayout::new(Direction::Horizontal);
    layout.add_child(ObjectId::new(), 1);
    layout.add_child(ObjectId::new(), 1);
    let image = harness.render_widget(|_painter| {});
    snapshot_assert("box_layout", &image);
}

#[test]
fn grid_layout_renders() {
    let Some(mut harness) = harness_or_skip("grid_layout_renders") else {
        return;
    };
    let mut layout = GridLayout::new();
    layout.add_cell(ObjectId::new(), 0, 0);
    layout.add_cell(ObjectId::new(), 0, 1);
    layout.add_cell(ObjectId::new(), 1, 0);
    layout.add_cell(ObjectId::new(), 1, 1);
    let image = harness.render_widget(|_painter| {});
    snapshot_assert("grid_layout", &image);
}
