name: Base Benchmarks

on:
  push:
    branches: master

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # libfontconfig1-dev: required by parley (yeslogic-fontconfig-sys)
          sudo apt-get install -y libfontconfig1-dev
      - uses: bencherdev/bencher@main
      - name: Track master benchmarks with Bencher
        run: |
          bencher run \
          --project quartzite \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --workspace
